// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAz3dvK771i-2w0-J2VEnCRdsCnid5CgZY',
    appId: '1:214187203412:android:6aee584003f36108cfc6c1',
    messagingSenderId: '214187203412',
    projectId: 'budgetboss1-ca211',
    storageBucket: 'budgetboss1-ca211.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-pJ-gyNpe1Wcd166ipX8Y_rIuhil9JTs',
    appId: '1:214187203412:ios:1db49c2b89a889accfc6c1',
    messagingSenderId: '214187203412',
    projectId: 'budgetboss1-ca211',
    storageBucket: 'budgetboss1-ca211.firebasestorage.app',
    iosClientId: '214187203412-ifafnkceegvgpn25tithg54or3f6bupm.apps.googleusercontent.com',
    iosBundleId: 'com.budgetboss.budgetbossApp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-pJ-gyNpe1Wcd166ipX8Y_rIuhil9JTs',
    appId: '1:214187203412:ios:1db49c2b89a889accfc6c1',
    messagingSenderId: '214187203412',
    projectId: 'budgetboss1-ca211',
    storageBucket: 'budgetboss1-ca211.firebasestorage.app',
    iosClientId: '214187203412-ifafnkceegvgpn25tithg54or3f6bupm.apps.googleusercontent.com',
    iosBundleId: 'com.budgetboss.budgetbossApp',
  );
}
